config/routes.rb
SecondSite::Application.routes.draw do
  resources :userinos

#  get "milks/showmethemilk"
#  get "pages/rootpage"
#  get "pages/talktome"
#  get "pages/whoami"

  # das darf spaeter weg
#  get "userinos/new"

  root :to => 'pages#rootpage'
  match '/newuserino',    :to => 'userinos#new'
  match '/rootpage',      :to => 'pages#rootpage'
  match '/talktome',      :to => 'pages#talktome'
  match '/whoami',        :to => 'pages#whoami'

  resources :milks
  match '/showmethemilk/:id', :to => 'milks#showmethemilk'

end

app/models/milk.rb
class Milk < ActiveRecord::Base
  attr_accessible :productname, :flavor, :milktype, :price
end

app/models/uzers.rb
# == Schema Information
#
# Table name: uzers
#
#  id         :integer         not null, primary key
#  namerino   :string(255)
#  emailino   :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Uzers < ActiveRecord::Base
  attr_accessible :namerino, :emailino
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/milks_controller.rb
class MilksController < ApplicationController

  # GET /showmethemilk/1
  # GET /showmethemilk/1.xml
  def showmethemilk
    @title = "A great encyclopaedia of available milks"
    #  @showmilk = Milk.find(9)
    @useroni = Uzers.find(1)

    @showmilk = Milk.find(params[:id])
    respond_to do |format|
      format.html # show showmethemilk.html.erb
      format.xml  { render :xml => @showmilk}
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def rootpage
    @title = "This is the root page, where everything starts"
  end

  def talktome
    @title = "Talk to me"
  end

  def whoami
    @title = "who am I"
  end
end

app/controllers/userinos_controller.rb
class UserinosController < ApplicationController
  def new
    @helpertitle ="Sign up"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # Return a title on a per-page basis.
  def helpertitle
    base_title = "Do it again"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
end

app/helpers/milks_helper.rb
module MilksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/userinos_helper.rb
module UserinosHelper
end

app/views/layouts/_footer.html.erb
<footer>
        <nav class="round">
          <ul>
            <li><%= link_to "Does", '#' %></li>
            <li><%= link_to "not", '#' %></li>
            <li><%= link_to "work", '#' %></li>
          </ul>
        </nav>
</footer>

app/views/layouts/_header.html.erb
      <header>
          <% logo = image_tag("logo.png", :alt => "Sample App", :class => "round") %>
          <%= link_to logo, root_path %>
        <nav class="round">
          <ul>
            <li><%= link_to "Root", rootpage_path %></li>
            <li><%= link_to "Talktome", talktome_path %></li>
            <li><%= link_to "WhoamiSignin", whoami_path %></li>
          </ul>
        </nav>
      </header>

app/views/layouts/_stylesheets.html.erb
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->    
    <%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
    <%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
    <!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
    <%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= helpertitle %></title>
    <%= render 'layouts/stylesheets' %>
  </head>
  <body>
    <div class="container">
      <%= render 'layouts/header' %>
      <section class="round">
        <%= yield %>
      </section>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/milks/showmethemilk.html.erb
<h1>Show me the Milk.</h1>
<p><%= @showmilk.productname  %>! Would you like to have it, <%= @useroni.namerino %>?</p>
<svg width="600" height="200" viewBox="0 0 600 200" preserveAspectRatio="xMinYMin slice" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<defs id="defs3371" />
 <g id="layer1"  transform="translate(0,0)">
       <rect width="160" height="40" x="20" y="10" id="cupUpperpart" class="<%= @showmilk.flavor  %>" />
       <path d="M 30,50 170,50 150,180 50,180 z" id="cupLowerpart"
       style="fill:#eeeeee;stroke:#000000;stroke-width:0px;stroke-linecap:butt;stroke-linejoin:miter;stroke-opacity:1" />
       <rect x ="90" y="<%= 180 - @showmilk.price  %>" height="<%= @showmilk.price  %>" width="20" id="prodrect" class="<%= @showmilk.flavor  %>"> </rect>
       <text class="productname" x="24" y="28" id="productname"><%= @showmilk.productname  %></text>
       <text class="milktype" x="24" y="44" id="milktype"><%= @showmilk.flavor  %> flavor <%= @showmilk.milktype  %></text>
       <text class="price" x="90" y="<%= 178 - @showmilk.price  %>" id="productname"><%= @showmilk.price  %> cent</text>
       <path d="M 0 180 L 600 180" class="outline"></path>
  </g>
</svg>

app/views/pages/rootpage.html.erb
<h1><%= @title %></h1>

<p>
  This is the home page for the
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  sample application.
</p>
<p>Would like to show something from a database here, but I can't.</p>
<%= link_to "Make yourself invited", newuserino_path, :class => "signup_button round" %>

app/views/pages/talktome.html.erb
<p>
  Contact Ruby on Rails Tutorial about the sample app at the
  <a href="http://railstutorial.org/feedback">feedback page</a>.
</p>

app/views/pages/whoami.html.erb
<p>
  <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/userinos/new.html.erb
<h1>Userinos#new</h1>
<p>Find me in app/views/userinos/new.html.erb</p>